# Generated by Django 6.0.3 on 2026-03-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadtype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Load Types'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Subscriptions'},
        ),
    ]
